# Generated by Django 3.0 on 2020-05-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('linkedin_url', models.TextField(max_length=200)),
                ('github_url', models.TextField(max_length=200)),
                ('about_member', models.TextField()),
                ('current_status', models.BooleanField()),
                ('college', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(max_length=200)),
                ('telegram_url', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('latitude', models.TextField(max_length=200)),
                ('longitude', models.TextField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('about_event', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('contact', models.TextField(max_length=200)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhattsappGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(max_length=200)),
                ('whattsapp_url', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.TextField(max_length=200)),
                ('github_account', models.TextField(max_length=200)),
                ('linkedin_account', models.TextField(max_length=200)),
                ('about_speaker', models.TextField(max_length=200)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserEvents')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.TextField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserEvents')),
            ],
        ),
    ]
