# Generated by Django 3.0 on 2020-05-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200518_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='about_speaker',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='github_account',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkedin_account',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speaker_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamposition',
            name='position',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='contact',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='group_name',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='telegram_url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='about_event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='latitude',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='longitude',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='contact',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='contact',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='group_name',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='whattsapp_url',
            field=models.TextField(max_length=100),
        ),
    ]
