# Generated by Django 3.0 on 2020-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200519_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='group_name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='telegram_url',
            field=models.CharField(max_length=100),
        ),
    ]
