# Generated by Django 3.0 on 2020-05-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200520_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='github_account',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkedin_account',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='college',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_status',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_url',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='telegram_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='group_name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='whattsappgroup',
            name='whattsapp_url',
            field=models.URLField(),
        ),
    ]
