# Generated by Django 3.0 on 2020-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200521_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamposition',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
