# Generated by Django 3.0 on 2020-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200524_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_image',
            field=models.ImageField(default='speaker_image/default.jpg', upload_to='speaker_image/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_image',
            field=models.ImageField(upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='cover_image',
            field=models.ImageField(default='event_image/default.jpg', upload_to='event_image/'),
        ),
        migrations.AlterField(
            model_name='usereventimage',
            name='album',
            field=models.ImageField(default='album_image/default.jpg', upload_to='album_image/'),
        ),
    ]
