# Generated by Django 3.0 on 2020-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200524_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user_image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
