# Generated by Django 3.0 on 2020-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200524_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_name',
            field=models.CharField(max_length=50),
        ),
    ]
